{% set name = "libusb1" %}
{% set version = "2.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/libusb1-{{ version }}.tar.gz
  sha256: d3ba82ecf7ab6a48d21dac6697e26504670cc3522b8e5941bd28fb56cf3f6c46

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - python >=3.4

test:
  imports:
    - usb1
    - usb1.__pyinstaller
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/vpelletier/python-libusb1
  summary: Pure-python wrapper for libusb-1.0
  license: LGPL-2.1-or-later
  license_file: COPYING.LESSER

extra:
  recipe-maintainers:
    - ickc
